[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Content-Encoding = "br"

[[headers]]
  for = "/*.wasm"
  [headers.values]
    Content-Type = "application/wasm"

[[headers]]
  for = "/*.data"
  [headers.values]
    Content-Type = "application/octet-stream"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"