[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "ALLOW-FROM https://telegram.org/"
    Content-Security-Policy = "frame-ancestors 'self' https://telegram.org/"

[[headers]]
  for = "/*.data"
  [headers.values]
    Content-Type = "application/octet-stream"

[[headers]]
  for = "/*.wasm"
  [headers.values]
    Content-Type = "application/wasm"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.gz"
  [headers.values]
    Content-Encoding = "gzip"

[build]
  publish = "."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200